# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build App'

- script: |
    CI=true npm run test
  displayName: 'Run tests'
  condition: "succeeded()"

- task: AzureCLI@1
  inputs:
    connectedServiceNameARM: 'Pay-As-You-Go(d0d640a9-bb06-4854-838d-4b4f31c0d40d)'
    scriptLocation: 'inlineScript'
    inlineScript: 'az storage blob upload-batch -d "$web" -s ./build --account-name $(Account.Name) --account-key $(Account.Key)'
  condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
