# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run build
  displayName: 'Build App'

- script: |
    cmd /C "set CI=true && npm run test"
  displayName: 'Run tests'
  condition: "succeeded()"

- task: AzureFileCopy@3
  inputs:
    SourcePath: './build'
    ConnectedServiceNameARM: 'Pay-As-You-Go(d0d640a9-bb06-4854-838d-4b4f31c0d40d)'
    Destination: 'AzureBlob'
    StorageAccountRM: 'playerstoragekmr'
    ContainerName: '$web'
  condition: "and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))"
